remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: ELLIS SYMPOSIUM on Machine Learning for Drug Discovery
description: ELLIS Symposium organized by [ELLIS Health}(https://ellis.eu/programs/ellis-health) and [ELLIS ML4Molecules](https://ellis.eu/programs/machine-learning-for-molecule-discovery)
# ELLIS SYMPOSIUM Machine Learning for Drug Discovery
