remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: ELLIS SYMPOSIUM on Machine Learning for Drug Discovery by Karsten Borgwardt and Günter Klambauer
description: ELLIS Symposium
# ELLIS SYMPOSIUM Machine Learning for Drug Discovery
