remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: ELLIS SYMPOSIUM on Machine Learning for Drug Discovery
description: ELLIS Symposium organized by ELLIS Health and ELLIS ML4Molecules
# ELLIS SYMPOSIUM Machine Learning for Drug Discovery
